### ISSUE TITLE
Error when used with userprofile with spaces

### ISSUE THREAD

**Issue by Hariama** [joskore/hyper-shellect#1]
![image](https://user-images.githubusercontent.com/18269973/50827473-d2614180-133e-11e9-9f2e-123229c1251a.png)

When hyper-shellect is used on a windows 10 machine with a userprofile which contains spaces, it redirects to the wrong path. I have replicated the following error on two machines with the same userprofile.

**Comment by joskore** [comment]
thanks for letting me know! this was a pretty straightforward fix, we're just quoting the run filepath. i've tested on my end and have no issues; let me know if it resolves on your end.

the update's been pushed to npm, so if you're running through hyper it should update automatically after a bit

**Comment by Hariama** [comment]
![image](https://user-images.githubusercontent.com/18269973/50849315-f2145c00-1376-11e9-8fa8-cf5e2439d5cf.png)

There is some progress, but a .json-file is now missing in the hyper-shellect folder. This might be a complete error on my side though, I'll try some things after class!

**Comment by joskore** [comment]
i made an update that should be creating that file if it doesn't exist, but it appears not to be working consistently. i'll keep working on that, but in the meantime i've added a placeholder to keep this particular error from happening.

let me know either way, thanks!

**Comment by Hariama** [comment]
![image](https://user-images.githubusercontent.com/18269973/50889969-89ba8e80-13f9-11e9-8648-092cff463872.png)


Okay, I have determined that the placeholder has no impact; whether it is in place or not, the same error occurs. Above I have included a more complete error-code, in which I read that the problem arises in line 43 of prompt.js, as an incorrect .json-file is read in by the async function selectShell(). This could be because the .env.json-file does not seem to get populated with data. If this is truly the case, and I understand correctly that the .env.json-file is for storing the different shells, and since no data is populated in this file, then by consequence the shellArray isn't populated correctly either, right?

**Comment by joskore** [comment]
thanks for the additional detail!

it looks like your current error may have been sourced in something i did in an attempt to fix your original error 😅 

in `index.js`, we write the shellect config object from `.hyper.js` to `.env.json` for us to play with. when you reported your initial problem, i switched from a plain templated string for the filepath to a path.join'd filepath which was referenced later. there's no reason i'm aware of that should cause that change to be problematic, but apparently there is one. i've switched back to the templated string and the error is no longer occurring on my end.

it's functional in osx, win server 2019 (with a user profile with spaces and one without). give it an update and let me know how it goes. sorry for the complications :/

**Comment by Hariama** [comment]
You were absolutely successful, your last fix did the trick! 😄
